repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(alembic/versions/|scripts|notebooks/utils)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: ^(alembic/versions/|notebooks/sprint-1/|notebooks/sprint-2/|notebooks/sprint-3/|notebooks/sprint-7/)
        additional_dependencies:
          - pydantic>=1.9.0,<2.0
          - SQLAlchemy>=2.0.12,<3.0
          - pandas-stubs>=2.0.2,<3.0
          - numpy>=1.25.1,<2.0
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--format=json"]
